### ISSUE TITLE
Milestone 1

### ISSUE THREAD

**Issue by fabricio-garcia** [fabricio-garcia/react-calculator#1]
- [x] Use `create-react-app` to initialize a new React app
- Documentation: [https://github.com/facebook/create-react-app](https://github.com/facebook/create-react-app)
- [x] Delete any unnecessary file or asset. 
- [x] Add the necessary packages to your project:
- Add [`big.js`](https://github.com/MikeMcl/big.js/) using npm
- [x] Run the application with `npm start` and make sure that everything works correctly.
- [x] Follow the instructions in `create-react-app-buildpack` to deploy the app to Heroku
- Initialize a git repo
- Create a Heroku app
- Commit and deploy to Heroku
- Make sure the Heroku app works correctly
- Push everything to Github
- Documentation: [https://github.com/mars/create-react-app-buildpack](https://github.com/mars/create-react-app-buildpack)
