### ISSUE TITLE
Milestone 2

### ISSUE THREAD

**Issue by fabricio-garcia** [fabricio-garcia/react-calculator#3]
## Microverse Requirements

- [x] Prepare the directory structure
- Create a components directory in the src folder.
- Create four files in there, each one representing one React component. For instance, the App component should be placed in src/components/App.js.
- [x] Implement the App component
- App should implement the render function.
- The render function should display Display and ButtonPanel.
- [x] Implement the Display component
- It should accept the result of the calculation as an incoming prop.
- The result prop should be a String.
- The default value of the result prop should be 0.
- [x] Implement the Button component
- It should accept a button name as a prop.
- The button name prop should be a String.
- [x] Implement the ButtonPanel component
- It should render the calculator panel with all the buttons in the following groups: (use divs to divide buttons into groups)
            Group 1: AC, +/-, %, ÷
            Group 2: 7, 8, 9, X
            Group 3: 4, 5, 6, -
            Group 4: 1, 2, 3, +
            Group 5: 0, ., =
