### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by fabricio-garcia** [fabricio-garcia/react-calculator#7]
## Microverse Requirements

- [x]  Preparation
- Create a new logic folder inside src and initialize two javascript files there: calculate.js and operate.js.
- Add the big.js package to your project dependencies.

- [x] Implement the calculate.js module
- It should contain one default method: calculate.
- The calculate method should accept a calculator data object and a button name as arguments.
- The calculator data object should contain three properties: total, next and operation.
- This method should use the buttonName argument to mutate the calculator’s data object and return its modified version. For instance if buttonName == "+/-", it should multiply total and next by -1 to make it negative or positive.

- [x] Implement the operate.js module
- It should import the big.js module from the corresponding npm package.
- It should implement one default function named operate.
- The operate function should accept numberOne, numberTwo and operation as arguments.
-  Using the value of the operation argument, this method should perform a simple math operation. For instance if operation == "-", it should return the result of subtracting the two passed numbers. Remember to wrap the numbers with big.js classes so you can operate on big numbers.
- If the buttonName in calculate.js is equal to any operation (e.g. +, -, x, ÷, % [modifier - turning the number into a percentage based number]), operate.js should be used to calculate the total property.

- [x]  Add calculate.js to the App component
- Import the calculate function.
